export const LOGIN_SUCCEESS = 'LOGIN_SUCCEESS';
export const LOAD_USER_DATA_SUCCESS = 'LOAD_USER_DATA_SUCCESS';
export const REQUIRE_CURRENT_USER_POSITION_SUCCESS = 'REQUIRE_CURRENT_USER_POSITION_SUCCESS';

export const LOAD_MEDIAS_SUCCESS = 'LOAD_MEDIAS_SUCCESS';
export const SELECT_MARKER = 'SELECT_MARKER';
export const FETCH_MEDIAS_REQUEST = 'FETCH_MEDIAS_REQUEST';

export const START_LOAD_USER_PROFILE_AJAX_CALL = 'START_LOAD_USER_PROFILE_AJAX_CALL';
export const FINISH_LOAD_USER_PROFILE_AJAX_CALL = 'FINISH_LOAD_USER_PROFILE_AJAX_CALL';
export const ERROR_LOAD_USER_PROFILE_AJAX_CALL = 'ERROR_LOAD_USER_PROFILE_AJAX_CALL';

export const START_LOAD_MEDIA_AJAX_CALL = 'START_LOAD_MEDIA_AJAX_CALL';
export const FINISH_LOAD_MEDIA_AJAX_CALL = 'FINISH_LOAD_MEDIA_AJAX_CALL';