export const LOGIN_SUCCEESS = 'LOGIN_SUCCEESS';
export const LOAD_USER_DATA_SUCCESS = 'LOAD_USER_DATA_SUCCESS';
export const REQUIRE_CURRENT_USER_POSITION_SUCCESS = 'REQUIRE_CURRENT_USER_POSITION_SUCCESS';

export const LOAD_MEDIAS_SUCCESS = 'LOAD_MEDIAS_SUCCESS';
export const SELECT_MARKER = 'SELECT_MARKER';